version: '3.8'
services:
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
