default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: 'localhost'

development:
  <<: *default
  database: pdf_master_development

test:
  <<: *default
  database: pdf_master_test

production:
  <<: *default
  database: pdf_master_production
  username: postgres
  password: postgres
  host: 'localhost'
