default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pdf_master_development
  username: postgres
  password: postgres
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

test:
  <<: *default
  database: pdf_master_test
  username: postgres
  password: postgres
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
